<script src="{{ asset('public/backend/assets/js/jquery-3.7.1.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/bootstrap.bundle.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/feather.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/jquery.slimscroll.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/apexchart/apexcharts.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/apexchart/chart-data.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/chartjs/chart.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/chartjs/chart-data.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/moment.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/bootstrap-datetimepicker.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/daterangepicker/daterangepicker.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/summernote/summernote-lite.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/select2/js/select2.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/%40simonwep/pickr/pickr.es5.min.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/todo.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/theme-colorpicker.js') }}" ></script>
<script src="{{ asset('public/backend/assets/js/script.js') }}" ></script>
<script src="{{ asset('public/backend/assets/plugins/toastr/toastr.min.js') }}"></script>
<script src="{{ asset('public/backend/assets/plugins/toastr/toastr.js') }}"></script>
<script src="{{ asset('public/backend/assets/plugins/sweetalert/sweetalert2.all.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
